# Generated by Django 5.2 on 2025-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migwaniapp', '0002_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('since_year', models.CharField(max_length=4)),
                ('logo', models.ImageField(blank=True, upload_to='partners/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
